# Generated by Django 5.1.4 on 2025-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
